spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edziennik
    username: admin
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug